### ISSUE TITLE
Change titles for 

### ISSUE THREAD

**Issue by cchampod** [sebastiansauer/yart#24]
Hello,
Many thanks for this excellent package. I have very basic question and please apologies for my ignorance. I would like to change the following default titles (from German in English):

- Zusammenfassung
- Tabellenverzeichnis
- Abbildungsverzeichnis
- Inhaltsverzeichnis

Where shall I act to adapt them?

Thanks a lot.
Christophe

**Comment by NMarkgraf** [comment]
As far as I know, Sebastian didi put them in yart! So in the YAML block a change from

"
lang: de-De
"

to
"
lang: en-Us
"

should work fine, didn't it?

**Comment by cchampod** [comment]
Many thanks, I should have look for thoroughly, it was in front of my eyes. Kind regards
