### ISSUE TITLE
Writing in Greek

### ISSUE THREAD

**Issue by MAlexGR** [sebastiansauer/yart#8]
First of all, Yart looks impressive into its "simplicity". A really good work!
My question is, how can I write in greek using XeLaTeX?  I'm writing mainly in greek so I want to take advantage of this beautiful package. Thank you in advance.

**Comment by NMarkgraf** [comment]
AFAIK, a 

```
output: 
  yart::yart
    pandoc_args: [
      "--pdf-engine=xelatex"
    ]
```

instead of just

```
output: 
  yart::yart
```

in the YAML-Block of the document should help here.

**Comment by MAlexGR** [comment]
@Norman. Thnk you for your response. Unfortunately this does not work. I
try it and got the following error:

"Error in yaml::yaml.load(string, ...) :
  Scanner error: mapping values are not allowed in this context at line 37,
column 14
Calls: <Anonymous> ... parse_yaml_front_matter -> yaml_load_utf8 ->
<Anonymous> -> .Call
Execution halted"

If you know any other tip to achieve greek writing with yart it would be
great.
In any case thank you for your effort.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Απαλλαγμένο
από ιούς. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-04-30 15:50 GMT+03:00 Norman Markgraf <notifications@github.com>:

**Comment by NMarkgraf** [comment]
BUT:

This just fixes the YAML block, but it won't work. - Sorry!

The problem is mainly in the resource code of yart:

```
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[$if(fontenc)$$fontenc$$else$T1$endif$]{fontenc}
  \usepackage[utf8]{inputenc}
```

This should change to:

```
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[$if(fontenc)$$fontenc$$else$T1$endif$]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provides euro and other symbols
\else % if luatex or xelatex
$if(mathspec)$
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{unicode-math}
  \fi
$else$
  \usepackage{unicode-math}
$endif$
```

Hope Sebastian will change it soon.

**Comment by NMarkgraf** [comment]
Sorry, Sebastian! - Du don't have to fix anything! - It works perfectly with:

```
output: 
  yart::yart:
    latex_engine: xelatex
```

But greek writers need some greek fonts in! ;-)

**Comment by NMarkgraf** [comment]
It should be possible to include any kind of tex file by:

```
output:
  yart::yart:
    includes:
      in_header: header.tex
      before_body: doc_prefix.tex
      after_body: doc_suffix.tex
```


your `header.tex` should look like:

```
\usepackage{xgreek}
```

I guess you don't really need before and after body, so you can reduce the YAML code to:

```
output:
  yart::yart:
    includes:
      in_header: header.tex
```

If you really want the intermediate tex file, add a `keep_tex: yes` like this:

```
output:
  yart::yart:
    keep_tex: yes
    includes:
      in_header: header.tex
```

And don't forget to write us, if it works! ;-)

Yours
Norman

**Comment by MAlexGR** [comment]
@NMarkgraf  Yep! worked flawlessly! You are right, I only need the in_header (for now) and "xltxtra" works better.

Norman you are the best. Thank you!
Alex

(Because you mention "no fear!", is it ok if I continue here with another Yart internals question (like changing German headings like "Zusammenfassung", with Greek ones) or should I open a new issue?)

**Comment by NMarkgraf** [comment]
A new issue for every new problem, please! -- That makes it easier for the developer, namely Sebastian here, too keep track of what is done and what needs to be done. -- But, that is my view. Sebastian should correct me, if I'm wrong.

**Comment by MAlexGR** [comment]
Ok I understand. So this issue is considered closed for me. Thank you again.
