### ISSUE TITLE
Changing predifined headings

### ISSUE THREAD

**Issue by MAlexGR** [sebastiansauer/yart#9]
Hello again. 

My question this time is, how can I change the normal tags/headings (like "zusammenfassung",  "Tabellenverzeichnis" etc) from german to greek lang. Also, in general (if you allow me a general question), what is the best path/process to customize a yart template in greek language (any tip?)?

**Comment by sebastiansauer** [comment]
Hi AIexGR,

In the YAML header of the yart-Rmd-file, there's a parameter called "lang". Currently it is set to "de-De", ie German. You can change it to Greek (please look up the correct value, maybe it is "gr"). After having changed that, the TOC etc. will have Greek names (if Greek is supported, but I assume it is).

Actually, that's the only parameter (or most important) to change to Greek.

Besides that, does the template work for you? Do you get your document compiled? Any other problems?

**Comment by NMarkgraf** [comment]
Hi @MAlexGR ,
moin Sebastian (aka @sebastiansauer),

according to [BCP-47](http://www.rfc-editor.org/rfc/rfc4646.txt) (formaly RFC 5646 which substitutes RFC 4646)  Greek is either "gr" or "gr-GR". You can check this [here](http://schneegans.de/lv/?tags=gr-GR&format=text).

Because you are using XeLaTeX, the package ["Polyglossia"](  https://ctan.org/pkg/polyglossia?lang=de) is in charge (and not "bable" as it is for LaTeX). You should take a look at the [manual of Polyglossia](http://ctan.mirrors.hoobly.com/macros/latex/contrib/polyglossia/polyglossia.pdf).

I bet it is a better idea to put a

```
\setdefaultlanguage{greek}
```

into the header, than *only* the 

```
lang: gr-GR
```
in the YAML block. This is because the "Bable-Way" (see 2.2 of the polyglossia manual)  is obsolete, but AFAIC used by Sebastians template.

Yours
Norman

**Comment by MAlexGR** [comment]
@sebastiansauer , @NMarkgraf  Hello guys!
Sebastian you are right that I need to change the `lang:` option to the right greek values (which btw are `el- EH` and I found that after some "pick and try" tests in the site Norman pointed). But changing these values isn't enough. They only enable to display greek words correctly, in pdf viewer's navication panel (bookmarks), not in text itself (in "real" document)! The headings in the text remain in german.

Norman, I tried then your suggestion by putting `\setdefaultlanguage{greek}` in "preamble.tex" but nothing. The knitr responded with:

`! Package polyglossia Error: The current roman font does not contain the Greek script! (polyglossia)                Please define \greekfont with \newfontfamily.`

 Then I did some work, searching for relevant errors and tried varius combinations, including: declairing font families ("`\setmainfont{...}`" etc), changing fonts, putting roman, serif etc fonts and everything else you can imagine, but always the same error.  Amongst the previous combinations, one and only one code structure worked:

```
\setmainfont{DejaVu Sans}
\setsansfont{DejaVu Sans}
\setmonofont{DejaVu Sans}
\newfontfamily\greekfont{TeX Gyre Termes}
\newfontfamily\greekfontsf{TeX Gyre Heros}
\newfontfamily\greekfonttt{TeX Gyre Cursor}
```

Don't ask me, I'm not a LaTeX guru so I don't know how and why it worked (although I have an idea).

All in all, with the above settings, I now have a beautiful, working and greek customized, yart document, thanks to you guys!

But, by searcing this issue I came to the conclusion that, there is **a problem** with `xelatex-polyglossia-various languages` combination as you can find [here](https://tex.stackexchange.com/questions/325774/polyglossia-multi-language-wrong-fonts-used?noredirect=1&lq=1), [here](https://tex.stackexchange.com/questions/348338/polyglossia-ignores-new-font-family-e-g-greekfont) and [here](https://tex.stackexchange.com/questions/349113/how-to-get-polyglossia-to-select-font-for-greek-script-automatically?noredirect=1&lq=1). The same applies not only for Greek but for Hebrew, Sanscrit and other languages also. Xelatex has a slight problem to detect correctly some fonts, when polyglossia is used. I know this isn't probably fair but I have to notice it.

Thank you both again for your time and effort spend to help me!
Yours Alex

ps: Although I'll close this issue, any suggestions, tips, "how to" or everything from you, will be welcomed.

**Comment by sebastiansauer** [comment]
I am not into these details as well, I have to say. Anyhow, seems you have a working solution by now. Enjoy!

**Comment by NMarkgraf** [comment]
Sorry Alex,

currently, as always ;-), not enough time to read all the stuff to find a better and more solid solution. 

Yours
Norman
